<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- Miqrasiyada xəta verməməsi üçün NuGet Audit-i söndürürük -->
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>

	<ItemGroup>
		<!-- Verilənlər bazası və EF Core paketləri -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<!-- Digər qatları tanımaq üçün referanslar -->
		<ProjectReference Include="..\Modules.Categories.Contracts\Modules.Categories.Contracts.csproj" />
		<ProjectReference Include="..\Modules.Products.Application\Modules.Products.Application.csproj" />
		<ProjectReference Include="..\Modules.Products.Contracts\Modules.Products.Contracts.csproj" />
		<ProjectReference Include="..\Modules.Products.Domain\Modules.Products.Domain.csproj" />
	</ItemGroup>

</Project>