<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- Bu sətir Controller, IActionResult və API xüsusiyyətlərini görmək üçündür -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<!-- Bu sətir IBasketModuleService, RequestBasketItem və s. Contract fayllarını görmək üçündür -->
		<ProjectReference Include="..\Common\Common.csproj" />
		<ProjectReference Include="..\Modules.Baskets.Contract\Modules.Baskets.Contract.csproj" />
	</ItemGroup>

</Project>